name: Feature request
description: Suggest an improvement related to webpage translation.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: need
    attributes:
      label: Translation problem to solve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Suggested experience
    validations:
      required: true
  - type: textarea
    id: privacy
    attributes:
      label: Privacy or permission impact

